config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "items#index"
  resources :items do
    resources :comments, only: :create

    collection do
      get 'limit'
    end
  end
end

app/models/allergy.rb
class Allergy < ApplicationRecord
  has_many :item_allergies
  has_many :items, through: :item_allergies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :item
  validates :text, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :item_allergies, dependent: :destroy
  has_many :allergies, through: :item_allergies
  has_many :comments, dependent: :destroy

  with_options presence: true do
    validates :image
    validates :name
    validates :text
    validates :allergy_ids
  end
end

app/models/item_allergy.rb
class ItemAllergy < ApplicationRecord
  belongs_to :item
  belongs_to :allergy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items
  has_many :comments

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'は英字と数字を両方とも含んでください'

  with_options presence: true do
    validates :nickname
    validates :first_name, format: { with: /\A[ぁ-んァ-ン一-龥]/, message: 'は漢字・ひらがな・カタカナのいずれかで入力してください' }
    validates :last_name, format: { with: /\A[ぁ-んァ-ン一-龥]/, message: 'は漢字・ひらがな・カタカナのいずれかで入力してください' }
    validates :birthday
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :first_name, :last_name, :birthday])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    ActionCable.server.broadcast 'comment_channel', content: @comment, username: @comment.user.nickname if @comment.save
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, item_id: params[:item_id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :limit]
  before_action :set_item, only: [:show, :destroy, :edit, :update]

  def index
    @items = Item.includes(:user).order('created_at DESC').page(params[:page]).per(16)
  end

  def limit
    @items = Item.includes(:allergies).where("allergies.id":1..7)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @item.comments.includes(:user).order('created_at DESC')
  end

  def destroy
    if @item.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  def edit
    redirect_to root_path unless current_user == @item.user
  end

  def update
    if @item.update(item_params)
      redirect_to item_path
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :image, :text, allergy_ids: []).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_item.html.erb
<li class='list'>
  <%= link_to item_path(item.id) do %>
    <div class='item-img-content'>
      <%= image_tag item.image, class: "item-img" %>
      <div class='item-info'>
        <h3 class='item-name'>
          <%= item.name %>
        </h3>
      </div>
    </div>
  <% end %>
</li>

app/views/items/edit.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to 'Food Selection', root_path, class:"items-sell-title"%>
  </header>
  
  <div class="items-sell-main">
    <h2 class="items-sell-title">食品の情報を入力</h2>
    <%= form_with model: @item, local: true do |f| %>

    <%= render 'shared/error_messages', model: @item %>

    <div class="img-upload">
      <div class="weight-bold-text">
        食品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <div class="new-items">
      <div class="weight-bold-text">
        食品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          食品の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :text, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（定価、注意点など)" ,rows:"7" ,maxlength:"1000" %>
      </div>
      <div class="items-explain">
        <div class="weight-bold-text">
          食品のアレルギー
          <span class="indispensable">必須</span>
        </div>
      </div>
      <% Allergy.all.each do |allergy| %>
        <%= f.check_box :allergy_ids, { multiple: true, checked: @item.allergies.find_by(id: allergy.id).present?, include_hidden: false }, allergy[:id] %>
        <label class='badge badge-secondary'><%= allergy.name %></label>
      <% end %>
    </div>
    <div class="sell-btn-contents">
      <%= f.submit "変更する" ,class:"sell-btn" %>
      <%=link_to 'もどる', item_path(@item.id), class:"back-btn" %>
    </div>
  </div>
  <% end %>
</div>
<%= render "shared/footer"%>

app/views/items/index.html.erb
<%= render "shared/header" %>
<div class='main'>

  <div class = 'title-contents'>
    <h2 class = 'service-title'>集まれ！！</h2>
    <h2 class = 'service-title'>アレルギー仲間たち</h2>
    <p class='service-explain'>
      食物アレルギーの人に参考にして欲しいサイトです
    </p>
  </div>

  <div class = 'important'>
    アレルギーは個人差が大きいので全ての方に対応している訳ではありません。ご自分の状態に合わせてお使いください。一切の責任は負いません。
  </div>

  <div class='item-contents'>
    <h2 class='title'>食品紹介</h2>
    <div class="subtitle">新規投稿商品</div>
    <%= link_to '主要７品目を含む食品はこちら', limit_items_path, class:"item-limit"%>
    <ul class='item-lists'>
      <% if @items.present? %>
        <%= render partial: 'item', collection: @items %>
      <% end %>
    </ul>
    <%= paginate @items %>
  </div>
  <div class = 'text-in'>
    <%= link_to '投稿する', new_item_path, class: "text-in-page"%>
  </div>
</div>

<%= render "shared/footer"%>

app/views/items/limit.html.erb
<%= render "shared/header" %>
<div class='main'>
<div class='item-contents'>
    <h2 class='title'>食品（アレルギー主要7品目を含む）</h2>
    <ul class='item-lists'>
      <% @items.each do |item| %>
        <li class='list'>
          <%= link_to item_path(item.id) do %>
            <div class='item-img-content'>
              <%= image_tag item.image, class: "item-img" %>
              <div class='item-info'>
              <h3 class='item-name'>
                <%= item.name %>
              </h3>
              </div>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class = 'text-in'>
    <%= link_to '投稿する', new_item_path, class: "text-in-page"%>
  </div>
</div>
<%= render "shared/footer"%>

app/views/items/new.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to 'Food Selection', root_path, class:"items-sell-title"%>
  </header>

  <div class="items-sell-main">
    <h2 class="items-sell-title">食品の情報を入力</h2>
    <%= form_with model: @item, local: true do |f| %>

    <%= render 'shared/error_messages', model: @item %>

    <div class="img-upload">
      <div class="weight-bold-text">
        食品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <div class="new-items">
      <div class="weight-bold-text">
        食品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          食品の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :text, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（定価、注意点など)" ,rows:"7" ,maxlength:"1000" %>
      </div>
      <div class="items-explain">
        <div class="weight-bold-text">
          食品のアレルギー
          <span class="indispensable">必須</span>
        </div>
      </div>
      <% Allergy.all.each do |allergy| %>
        <%= f.check_box :allergy_ids, { multiple: true, checked: @item.allergies.find_by(id: allergy.id).present?, include_hidden: false }, allergy[:id] %>
        <label><%= allergy.name %></label>
      <% end %>
    </div>
    <div class="sell-btn-contents">
      <%= f.submit "紹介する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
  </div>
  <% end %>
</div>
<%= render "shared/footer"%>

app/views/items/show.html.erb
<%= render "shared/header" %>

<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @item.name %>
    </h2>
    <div class='item-img-content'>
      <%= image_tag @item.image ,class:"item-box-img" %>
    </div>

    <% if user_signed_in? && current_user.id == @item.user.id %>
      <%= link_to '商品の編集', edit_item_path(@item.id), method: :get, class: "item-red-btn" %>
      <p class='or-text'>or</p>
      <%= link_to '削除', item_path(@item.id), method: :delete, class:'item-destroy' %>
    <% end %>

    <div class="item-explain-box">
      <span><%= @item.text %></span>
    </div>
    <div class="detail-item">＜紹介者＞
      <div class="detail-value"><%= @item.user.nickname %></div>
    </div>
    <div class="detail-item">＜アレルギー＞
      <div class="allergies">
      <% @item.allergies.order('id').each do |allergy| %>
        <div class="allergy">
          <div class="allergy-name">
            <%= allergy.name%>
          </div>
        </div>
      <% end %>
      </div>
    </div>
  </div>
  <div class="comment-box">
    <% if current_user %> 
      <%= form_with model: [@item,@comment] do |f| %>
        <%= f.text_area :text, class:"comment-text", rows: "3", maxlength:"88"%>
        <p class="comment-warn">
           相手のことを考え丁寧なコメントを心がけましょう。
          <br>
          不快な言葉遣いなどは利用制限や退会処分となることがあります。
        </p>
        <%=f.submit "コメントする", class:"comment-btn" %>
      <% end %>
    <% else %>
      <h1> コメントの投稿には新規登録/ログインが必要です </h1>
    <% end %> 
    ＜コメント一覧＞
    <div id="comments">
      <% if @comments %>
        <% @comments.each do |comment| %>
          <p> 
            <strong><%= comment.user.nickname %> : </strong>
            <%= comment.text %> 
          </p> 
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="links">
    <%= link_to "＜ 前の商品", "#", class:"change-item-btn"%>
    <%= link_to "後ろの商品 ＞", "#", class:"change-item-btn"%>
  </div>
</div>

<%= render "shared/footer"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodSelection</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class='footer'>
</div>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to 'Food Selection', "/", class:"food-selection" %>
    <ul class='nav'>
      <li><%= link_to 'アレルギー', "#", class: "category-list" %></li>
      <% if user_signed_in? %>
        <li><%= link_to current_user.nickname, "#", class: "user-nickname" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %> 
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>プライバシーポリシー</p>
    <p class='second-fotter-text'>Food Selection利用規約</p>
    <p class='second-fotter-text'>特定商取引に関する表記</p>
  </div>
  <div class="second-fotter-title">
    Food Selection
  </div>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%=link_to 'Food Selection', "/", class: "second-name" %>
</header>